version: '3.7'
services:
  nginx:
    hostname: 'nginx'
    container_name: 'nginx'
    image: nginx:stable-alpine
    ports:
      - 80:8080
      - 9443:9443
    environment:
     - NGINX_HOST=jprq.io
     - NGINX_PORT=80
    volumes:
     - ./configs/nginx/templates:/etc/nginx/templates
    depends_on:
     - "prometheus"
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - ~/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker

  portainer:
    hostname: 'portainer'
    container_name: portainer
    image: portainer/portainer-ce:latest
    # command: -H unix:///var/run/docker.sock
    ports:
      - "7000:8000"
      # - "9443:9443"
    # restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
