name: Makefile CI

on:
  workflow_dispatch:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

jobs:
  jenkins:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install pkgs
      run: |
        pip install jprq

    - name: Install dependencies
      run: make up

    - name: configure tunnel
      run: |
        make live
        jprq tcp 22

    - name: Run distcheck
      run: make distcheck
